In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.1.3


In [4]:
list = [1,2,3,4,5]

In [5]:
print(list)

[1, 2, 3, 4, 5]


In [6]:
print(list * 2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [7]:
array = np.array([1,2,3,4,5])

In [8]:
print(array)

[1 2 3 4 5]


In [9]:
print(array * 2)

[ 2  4  6  8 10]


In [10]:
print(array +1)

[2 3 4 5 6]


In [13]:
print(array[0],[3])

1 [3]


In [15]:
array = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

In [16]:
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
print(array * 2)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [36]:
print(array[0:,1])
print(array[1,3])

[ 2  6 10]
8


In [37]:
print(array[0:2,1])

[2 6]


In [38]:
print(array[1:,3])

[ 8 12]


In [39]:
print(array[1:,2:])

[[ 7  8]
 [11 12]]


In [40]:
print(array[1:3,2:4])

[[ 7  8]
 [11 12]]


In [41]:
array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]
                 ])


In [43]:
print(array[0:5,0:2] * 2)

[[ 2  4]
 [10 12]
 [18 20]
 [26 28]]


In [44]:
array = np.array([[["A","B","C"],["D","E","F"],["G","H","I"]],
                  [["J","K","L"],["M","N","O"],["P","Q","R"]],
                  [["S","T","U"],["V","W","X"],["Y","Z"," "]]])

In [46]:
print(array.ndim)
print(array.shape)

3
(3, 3, 3)


In [48]:
# Form a word prince using the multidimensional indexing{LRC-Rule}
print(array[1,2,0] + array[1,2,2] + array[0,2,2] + array[1,1,1] + array[0,0,2] + array[0,1,1])

PRINCE


In [57]:
#slicing
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])


In [58]:
print(array[0])

[1 2 3 4]


In [59]:
print(array[2])

[ 9 10 11 12]


In [60]:
print(array[0:2])

[[1 2 3 4]
 [5 6 7 8]]


In [62]:
print(array[::-1])

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [64]:
# Column Selection
print(array[1,3])

8


In [66]:
print(array[0:, 1])

[ 2  6 10 14]


In [67]:
print(array[0:, -1])

[ 4  8 12 16]


In [68]:
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [69]:
print(array[1:4, 0:3])

[[ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [70]:
# Scalar Arithmetic
array = np.array([1,2,3,4])
print(array + 1)
print(array - 1)
print(array * 2)
print(array / 4)
print(array ** 5)

[2 3 4 5]
[0 1 2 3]
[2 4 6 8]
[0.25 0.5  0.75 1.  ]
[   1   32  243 1024]


In [73]:
# Vectorized math function
array = np.array([1,2,3,4.6,3.3])
print(np.sqrt(array))
print(np.round(array))
print(np.floor(array)) # always round down
print(np.ceil(array)) # always round up 

[1.         1.41421356 1.73205081 2.14476106 1.81659021]
[1. 2. 3. 5. 3.]
[1. 2. 3. 4. 3.]
[1. 2. 3. 5. 4.]


In [74]:
# Area of cicle using 
radius = np.array([2,4,6,7])
print(np.pi * radius**2)


[ 12.56637061  50.26548246 113.09733553 153.93804003]


In [75]:
# Element Wise Arithematic
array1 = np.array([1,2,3,4])
array2 = np.array([5,6,7,8])
print(array1 + array2)

[ 6  8 10 12]


In [76]:
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)


[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[    1    64  2187 65536]


In [82]:
# Broadcasting: allows numpy to Perform operations on array with different shapes by vertically expanding their dimensions
# rule: The dimensions have same size or one of them is having size of one 
array1 = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]])
array2 = np.array([[1],[2],[3]])
print(np.shape(array1))
print(np.shape(array2))

(3, 4)
(3, 1)


In [84]:
print(array1)
print(array2)
print(array1 + array2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1]
 [2]
 [3]]
[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]]


In [88]:
# Print the table 1 to 10 by using broadcasting 
table1_array = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])
table2_array = np.array([[1,2,3,4,5,6,7,8,9,10]])
print(np.shape(table1_array))
print(np.shape(table2_array))
print(table1_array)
print(table2_array)
print(table2_array * table1_array)

(10, 1)
(1, 10)
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[ 1  2  3  4  5  6  7  8  9 10]]
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [95]:
# Aggregate Functions
array = np.array([1,2,3,4,500])
print(np.max(array))
print(np.min(array))
print(np.std(array))
print(np.median(array))
print(np.mean(array))
print(np.sum(array))
print(np.sqrt(array))
print(np.var(array))  # squar of the SD

500
1
199.00251254695254
3.0
102.0
510
[ 1.          1.41421356  1.73205081  2.         22.36067977]
39602.0


In [97]:
# Shape of the particular value
print(np.argmin(array))
print(np.argmax(array))

0
4


In [105]:
array = np.array([[1,2,3,4],
                  [5,6,7,8]])
print(np.sum(array,axis = 0)) # sum all the column
print(np.sum(array,axis = 1))  # Sum all the row

[ 6  8 10 12]
[10 26]


In [109]:
# Filtering 
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(f"Even: {array[array%2 == 0]}")






Even: [ 2  4  6  8 10 12 14 16 18 20]
